version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 16 * * *"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: "dotnet-sdk"
    directory: "/test"
    schedule:
      interval: "daily"
      time: "17:00"
