version: 2
registries:
  ruby-github:
    type: rubygems-server
    url: rubygems.pkg.github.com/github
    token: ${{secrets.CONTAINER_BUILDER_TOKEN}}
  ghcr:
    type: docker-registry
    url: ghcr.io
    username: PAT
    password: ${{secrets.CONTAINER_BUILDER_TOKEN}}
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    registries:
      - "ghcr"
    labels:
      - dependencies
      - docker
      - Fanout
    groups:
      gh-base-image:
        patterns:
        - "github/gh-base-image*"
  - package-ecosystem: "docker"
    directory: "/proto/dependabot-api"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    labels:
      - dependencies
      - docker
      - Fanout
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    ignore:
      - dependency-name: "github/internal-actions"
    labels:
      - dependencies
      - github_actions
      - Fanout
  - package-ecosystem: "bundler"
    insecure-external-code-execution: allow
    directory: "/"
    open-pull-requests-limit: 99
    vendor: true
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    registries:
      - "ruby-github"
    labels:
      - dependencies
      - bundler
      - Fanout
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-types:
        - "patch"
        - "minor"
      internal-dependencies:
        patterns:
        - "activejob-scheduled_job"
        - "aqueduct-rails"
        - "azure-storage-blob"
        - "chatops-controller"
        - "dependabot-update-job-runner"
        - "diet_earthsmoke"
        - "failbot"
        - "feature-flags-client"
        - "fido-challenger-client"
        - "github_chatops_extensions"
        - "github-launch"
        - "github-telemetry"
        - "hydro-client"
        - "monolith-twirp-*"
        - "proto-dependabot-api"
        - "trilogy_adapter"
      dependabot:
        patterns:
        - "dependabot*"
      oss-dependencies:
        update-types:
        - "minor"
        - "patch"
        patterns:
        - "activejob-retry"
        - "active_model_serializers"
        - "aws-sdk-*"
        - "base62"
        - "coach"
        - "dogstatsd-ruby"
        - "excon"
        - "faraday-retry"
        - "flipper"
        - "flipper-active_record"
        - "freno-client"
        - "google-protobuf"
        - "graphql-client"
        - "json-schema"
        - "jwt"
        - "lightstep"
        - "nokogiri"
        - "octokit"
        - "prius"
        - "puma"
        - "rack-cors"
        - "rails"
        - "rbnacl"
        - "redis"
        - "resqued"
        - "scientist"
        - "scrolls"
        - "slop"
        - "statesman"
        - "statsd-ruby"
        - "terminal-table"
        - "toml-rb"
        - "trilogy"
        - "twirp"
        - "tzinfo"
        - "tzinfo-data"
      oss-dependencies-major:
        update-types:
        - "major"
        patterns:
        - "activejob-retry"
        - "active_model_serializers"
        - "aws-sdk-*"
        - "base62"
        - "coach"
        - "dogstatsd-ruby"
        - "excon"
        - "faraday-retry"
        - "flipper"
        - "flipper-active_record"
        - "freno-client"
        - "google-protobuf"
        - "graphql-client"
        - "json-schema"
        - "jwt"
        - "lightstep"
        - "nokogiri"
        - "octokit"
        - "prius"
        - "puma"
        - "rack-cors"
        - "rails"
        - "rbnacl"
        - "redis"
        - "resqued"
        - "scientist"
        - "scrolls"
        - "slop"
        - "statesman"
        - "statsd-ruby"
        - "terminal-table"
        - "toml-rb"
        - "trilogy"
        - "twirp"
        - "tzinfo"
        - "tzinfo-data"
  - package-ecosystem: "bundler"
    directory: "/vendor/activejob-scheduled_job"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    labels:
      - dependencies
      - bundler
      - Fanout
  - package-ecosystem: "gomod"
    directory: "/proto/dependabot-api"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    labels:
      - dependencies
      - go
      - Fanout
  # GHES release branches
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "enterprise-3.12-release"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    registries:
      - "ghcr"
    labels:
      - dependencies
      - docker
      - Fanout
      - "ern:not-customer-facing"
    ignore:
      - dependency-name: ruby
    groups:
      ghes-3.12-base-image:
        patterns:
        - "github/gh-base-image*"
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "enterprise-3.13-release"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    registries:
      - "ghcr"
    labels:
      - dependencies
      - docker
      - Fanout
      - "ern:not-customer-facing"
    ignore:
      - dependency-name: ruby
    groups:
      ghes-3.13-base-image:
        patterns:
        - "github/gh-base-image*"
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "enterprise-3.14-release"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    registries:
      - "ghcr"
    labels:
      - dependencies
      - docker
      - Fanout
      - "ern:not-customer-facing"
    ignore:
      - dependency-name: ruby
    groups:
      ghes-3.14-base-image:
        patterns:
        - "github/gh-base-image*"
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "enterprise-3.15-release"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    registries:
      - "ghcr"
    labels:
      - dependencies
      - docker
      - Fanout
      - "ern:not-customer-facing"
    ignore:
      - dependency-name: ruby
    groups:
      ghes-3.15-base-image:
        patterns:
        - "github/gh-base-image*"
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "enterprise-3.16-release"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    registries:
      - "ghcr"
    labels:
      - dependencies
      - docker
      - Fanout
      - "ern:not-customer-facing"
    ignore:
      - dependency-name: ruby
    groups:
      ghes-3.16-base-image:
        patterns:
        - "github/gh-base-image*"
  - package-ecosystem: "terraform"
    directory: "/terraform/staff-wus2-01/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "terraform"
    directory: "/terraform/prod-sdc-01/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
  - package-ecosystem: "terraform"
    directory: "/terraform/prod-weu-01/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
